server:
  port: 8001

dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://localhost:2181
    timeout: 6000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: info.lostred.provider.service